### ISSUE TITLE
New to Gulp but Seems Like it Should Be Working

### ISSUE THREAD

**Issue by LindseyLeanne** [wirecss/wire.css#7]
Anytime I update the _.config.scss file - I keep getting the below error with Gulp running (and CSS doesn't compile):

'sass' errored after 4.79 ms
[12:17:07] TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at Module.require (internal/modules/cjs/loader.js:631:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireFn (/Users/lindseyjones/Github/sitename/node_modules/gulp-load-plugins/index.js:37:14)
    at Object.get (/Users/lindseyjones/Github/sitename/node_modules/gulp-load-plugins/index.js:68:18)
    at Gulp.<anonymous> (/Users/lindseyjones/Github/sitename/gulpfile.js:44:21)
    at module.exports (/Users/lindseyjones/Github/sitename/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/lindseyjones/Github/sitename/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/lindseyjones/Github/sitename/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/lindseyjones/Github/sitename/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Users/lindseyjones/Github/sitename/node_modules/gulp/index.js:36:18)

Am I missing something that should be installed with the framework? Thank you,

**Comment by LindseyLeanne** [comment]
@perichus actually I got gulp to run the compiler and the files within the SCSS folder are updating to the wire.css but not to wire.min.css. The original problem was that I needed to install gulp sass and gulp-load-plugins via npm. Appreciate any insight on this last quirk and apologies if it's user error.. Thanks so much
